### PR TITLE
Added support for Scala Native

### PR DESCRIPTION
**Pull request by TonioGela**
As per the title, I added the native build for this excellent repo. I had to increase a few versions, mainly because the native versions of this project's dependencies were published later than the versions the project was using. Also, I had to increase the Scala version to `3.3.0` as the latest circe version was published for `3.2.2`, and the project was stuck to `3.0.1`.
I hope you'll appreciate it and I can't wait for the first native release :D

### CODE REVIEW

**Comment by TonioGela** [comment]
Also, I can provide some help setting up the build using `sbt-typelevel`, to automatically write the github actions and so on, let me know

**Comment by abdolence** [comment]
Thanks for your contributions 👍🏻
It is great to see Scala is still have some people working on things. I'll review it soon. I've glanced through already it didn't see any issue. I just need to verify GitHub settings and actions first.

**Comment by TonioGela** [comment]
> It is great to see Scala is still have some people working on things.

Count on me :D
I'll cite this library in a blog post soon, I'll let you know :D

> I've glanced through already it didn't see any issue. I just need to verify GitHub settings and actions first.

Let me know if I can help. It would be awesome to have a `0.10.2` that has both native support and `Codec`s definitions (see my other PR)

~~Also, I might open another PR to update the plugins versions or include it here~~ Done, also I re-enabled the tests on all the platforms

Cheers

**Review by abdolence — APPROVED** [review]
Awesome updates, thanks again 🏆 
Additionally grateful for updating README, people tend to forget it.

I'm going to release v0.11, since I think this is more just bug fixing or minor adjustments.

**Comment by TonioGela** [comment]
Thank you :) Please include the other PR too if possible 😇

**Comment by abdolence** [comment]
Of course, they are all released now:
https://github.com/abdolence/circe-tagged-adt-codec-scala3/releases/tag/v0.11.0

Let me know if anything off.

**Comment by TonioGela** [comment]
Thank you!

**Comment by TonioGela** [comment]
Works flawlessly in scala-cli :)

```scala
//> using scala 3.3.0
//> using platform native
//> using dep org.latestbit::circe-tagged-adt-codec::0.11.0

import io.circe.syntax.EncoderOps
import org.latestbit.circe.adt.codec.JsonTaggedAdt

enum TestEvent derives JsonTaggedAdt.Codec {
  case Event1(anyYourField : String)
  case Event2(anyOtherField : Long)
}

@main def printAdt() = println((TestEvent.Event1("foo"):TestEvent).asJson.noSpaces)
```

**Comment by abdolence** [comment]
> using platform native

I didn't know you can do it with native, cool stuff 👍🏻

**Pull request merged**
